In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
dataset = pd.read_csv('C:/Users/Som/Desktop/Datasets/Housing_Modified.csv',header=None)
dataset

,0,1,2,3,4,5,6,7,8,9,10,11
0,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
1,42000,5850,3,1,two,yes,no,yes,no,no,1,no
2,38500,4000,2,1,one,yes,no,no,no,no,0,no
3,49500,3060,3,1,one,yes,no,no,no,no,0,no
4,60500,6650,3,1,two,yes,yes,no,no,no,0,no
5,61000,6360,2,1,one,yes,no,no,no,no,0,no
6,66000,4160,3,1,one,yes,yes,yes,no,yes,0,no
7,66000,3880,3,2,two,yes,no,yes,no,no,2,no
8,69000,4160,3,1,three,yes,no,no,no,no,0,no
9,83800,4800,3,1,one,yes,yes,yes,no,no,0,no
10,88500,5500,3,2,four,yes,yes,no,no,yes,1,no
11,90000,7200,3,2,one,yes,no,yes,no,yes,3,no
12,30500,3000,2,1,one,no,no,no,no,no,0,no
13,27000,1700,3,1,two,yes,no,no,no,no,0,no
14,36000,2880,3,1,one,no,no,no,no,no,0,no
15,37000,3600,2,1,one,yes,no,no,no,no,0,no
16,37900,3185,2,1,one,yes,no,no,no,yes,0,no
17,40500,3300,3,1,two,no,no,no,no,no,1,no
18,40750,5200,4,1,three,yes,no,no,no,no,0,no
19,45000,3450,1,1,one,yes,no,no,no,no,0,no
20,45000,3986,2,2,one,no,yes,yes,no,no,1,no
21,48500,4785,3,1,two,yes,yes,yes,no,yes,1,no
22,65900,4510,4,2,two,yes,no,yes,no,no,0,no
23,37900,4000,3,1,two,yes,no,no,no,yes,0,no
24,38000,3934,2,1,one,yes,no,no,no,no,0,no
25,42000,4960,2,1,one,yes,no,no,no,no,0,no
26,42300,3000,2,1,two,yes,no,no,no,no,0,no
27,43500,3800,2,1,one,yes,no,no,no,no,0,no
28,44000,4960,2,1,one,yes,no,yes,no,yes,0,no
29,44500,3000,3,1,one,no,no,no,no,yes,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
517,95000,6000,3,2,three,yes,yes,no,no,yes,0,no
518,96500,6000,4,2,four,yes,no,no,no,yes,0,no
519,101000,6240,4,2,two,yes,no,no,no,yes,1,no
520,102000,6000,3,2,two,yes,yes,no,no,no,1,no
521,103000,7680,4,2,four,yes,yes,no,no,yes,1,no
522,105000,6000,4,2,four,yes,yes,no,no,yes,1,no
523,108000,6000,4,2,four,yes,no,no,no,yes,1,no
524,110000,6000,4,2,four,yes,no,no,no,no,2,no
525,113000,6000,4,2,four,yes,no,no,no,yes,1,no
526,120000,7475,3,2,four,yes,no,no,no,yes,2,no
527,105000,5150,3,2,four,yes,no,no,no,yes,2,no
528,106000,6325,3,1,four,yes,no,no,no,yes,1,no
529,107500,6000,3,2,four,yes,no,no,no,yes,1,no
530,108000,6000,3,2,three,yes,no,no,no,yes,0,no
531,113750,6000,3,1,four,yes,yes,no,no,yes,2,no
532,120000,7000,3,1,four,yes,no,no,no,yes,2,no
533,70000,12900,3,1,one,yes,no,no,no,no,2,no
534,71000,7686,3,1,one,yes,yes,yes,yes,no,0,no
535,82000,5000,3,1,three,yes,no,no,no,yes,0,no
536,82000,5800,3,2,four,yes,no,no,no,yes,0,no
537,82500,6000,3,2,four,yes,no,no,no,yes,0,no
538,83000,4800,3,1,three,yes,no,no,no,yes,0,no
539,84000,6500,3,2,three,yes,no,no,no,yes,0,no
540,85000,7320,4,2,two,yes,no,no,no,no,0,no
541,85000,6525,3,2,four,yes,no,no,no,no,1,no
542,91500,4800,3,2,four,yes,yes,no,no,yes,0,no
543,94000,6000,3,2,four,yes,no,no,no,yes,0,no
544,103000,6000,3,2,four,yes,yes,no,no,yes,1,no
545,105000,6000,3,2,two,yes,yes,no,no,yes,1,no
546,105000,6000,3,1,two,yes,no,no,no,yes,1,no

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 12 columns):
0     547 non-null object
1     547 non-null object
2     547 non-null object
3     547 non-null object
4     547 non-null object
5     547 non-null object
6     547 non-null object
7     547 non-null object
8     547 non-null object
9     547 non-null object
10    547 non-null object
11    547 non-null object
dtypes: object(12)
memory usage: 51.4+ KB